### ISSUE TITLE
Failed to build on IOS

### ISSUE THREAD

**Issue by ben55j** [pikaju/flutter-maps-launcher#11]
Hello,

The package works well on my IOS simulator, but the build failed when I run it on my device.

Any idea about how to fix ?
thank you.

--------------------------------------------------------

Failed to build iOS app
Error output from Xcode build:
↳
    2021-01-11 20:25:43.992 xcodebuild[4730:4360517]  DVTAssertions: Warning in
    /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 62cdf2dab688e03ecf77f1cfc4a6f43305f211e6 was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7fd27d53a830>
    Method:   -platform
    Thread:   <NSThread: 0x7fd27bd369d0>{number = 7, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2021-01-11 20:25:44.228 xcodebuild[4730:4360516]  DVTAssertions: Warning in
    /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 62cdf2dab688e03ecf77f1cfc4a6f43305f211e6 was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7fd27d53a830>
    Method:   -platform
    Thread:   <NSThread: 0x7fd27d37a270>{number = 9, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/benjaminazogui/Development/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+17/ios/Classes/FLTImagePickerPlugin.m:14
    9:20: warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of
    UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
        [[[UIAlertView alloc] initWithTitle:NSLocalizedString(@"Error", nil)
                       ^
    In module 'UIKit' imported from /Users/benjaminazogui/Development/Projects/gitProjects/Service Adom Pro/services_adom_pro/ios/Pods/Target Support
    Files/image_picker/image_picker-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk/System/Library/Frameworks/UIKit.framework/He
    aders/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    1 warning generated.
    ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
    ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
    ld: warning: Could not find or use auto-linked library 'swiftCore'
    ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
    ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
    ld: warning: Could not find or use auto-linked library 'swiftCompatibility50'
    ld: warning: Could not find or use auto-linked library 'swiftDarwin'
    ld: warning: Could not find or use auto-linked library 'swiftUIKit'
    ld: warning: Could not find or use auto-linked library 'swiftCompatibility51'
    ld: warning: Could not find or use auto-linked library 'swiftFoundation'
    ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
    ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements'
    ld: warning: Could not find or use auto-linked library 'swiftMetal'
    ld: warning: Could not find or use auto-linked library 'swiftDispatch'
    ld: warning: Could not find or use auto-linked library 'swiftCoreMedia'
    ld: warning: Could not find or use auto-linked library 'swiftCoreAudio'
    Undefined symbols for architecture arm64:
      "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
          __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_maps_launcher)
      "__swift_FORCE_LOAD_$_swiftCompatibility51", referenced from:
          __swift_FORCE_LOAD_$_swiftCompatibility51_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility51_$_maps_launcher)
      "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
          __swift_FORCE_LOAD_$_swiftCompatibility50_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility50_$_maps_launcher)
      "__swift_FORCE_LOAD_$_swiftCoreAudio", referenced from:
          __swift_FORCE_LOAD_$_swiftCoreAudio_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreAudio_$_maps_launcher)
      "type metadata for Swift.String", referenced from:
          maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
          function signature specialization <Arg[0] = Dead, Arg[1] = Dead, Arg[2] = Owned To Guaranteed> of function signature specialization <Arg[1] =
          [Closure Propagated : reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.Optional<Swift.AnyObject>)
          -> () to @escaping @callee_guaranteed (@in_guaranteed Swift.Optional<Any>) -> (), Argument Types : [@escaping @callee_unowned
          @convention(block) (@unowned Swift.AnyObject?) -> ()]> of maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result:
          (Any?) -> ()) -> () in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "_swift_bridgeObjectRelease", referenced from:
          maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
          function signature specialization <Arg[0] = Dead, Arg[1] = Dead, Arg[2] = Owned To Guaranteed> of function signature specialization <Arg[1] =
          [Closure Propagated : reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.Optional<Swift.AnyObject>)
          -> () to @escaping @callee_guaranteed (@in_guaranteed Swift.Optional<Any>) -> (), Argument Types : [@escaping @callee_unowned
          @convention(block) (@unowned Swift.AnyObject?) -> ()]> of maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result:
          (Any?) -> ()) -> () in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "__swift_FORCE_LOAD_$_swiftCoreMedia", referenced from:
          __swift_FORCE_LOAD_$_swiftCoreMedia_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreMedia_$_maps_launcher)
      "__swift_FORCE_LOAD_$_swiftCoreImage", referenced from:
          __swift_FORCE_LOAD_$_swiftCoreImage_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreImage_$_maps_launcher)
      "__swift_FORCE_LOAD_$_swiftCoreGraphics", referenced from:
          __swift_FORCE_LOAD_$_swiftCoreGraphics_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreGraphics_$_maps_launcher)
      "__swift_FORCE_LOAD_$_swiftQuartzCore", referenced from:
          __swift_FORCE_LOAD_$_swiftQuartzCore_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftQuartzCore_$_maps_launcher)
      "_swift_release", referenced from:
          ___swift_destroy_boxed_opaque_existential_0 in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "__swift_FORCE_LOAD_$_swiftDispatch", referenced from:
          __swift_FORCE_LOAD_$_swiftDispatch_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftDispatch_$_maps_launcher)
      "__swift_FORCE_LOAD_$_swiftCoreFoundation", referenced from:
          __swift_FORCE_LOAD_$_swiftCoreFoundation_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreFoundation_$_maps_launcher)
      "_swift_getInitializedObjCClass", referenced from:
          static maps_launcher.SwiftMapsLauncherPlugin.register(with: __C.FlutterPluginRegistrar) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
          type metadata accessor for maps_launcher.SwiftMapsLauncherPlugin in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
          @objc static maps_launcher.SwiftMapsLauncherPlugin.register(with: __C.FlutterPluginRegistrar) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
          maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
          function signature specialization <Arg[0] = Dead, Arg[1] = Dead, Arg[2] = Owned To Guaranteed> of function signature specialization <Arg[1] =
          [Closure Propagated : reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.Optional<Swift.AnyObject>)
          -> () to @escaping @callee_guaranteed (@in_guaranteed Swift.Optional<Any>) -> (), Argument Types : [@escaping @callee_unowned
          @convention(block) (@unowned Swift.AnyObject?) -> ()]> of maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result:
          (Any?) -> ()) -> () in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "__swift_FORCE_LOAD_$_swiftFoundation", referenced from:
          __swift_FORCE_LOAD_$_swiftFoundation_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftFoundation_$_maps_launcher)
      "value witness table for Builtin.UnknownObject", referenced from:
          full type metadata for maps_launcher.SwiftMapsLauncherPlugin in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "(extension in Foundation):Swift.String._bridgeToObjectiveC() -> __C.NSString", referenced from:
          static maps_launcher.SwiftMapsLauncherPlugin.register(with: __C.FlutterPluginRegistrar) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
          @objc static maps_launcher.SwiftMapsLauncherPlugin.register(with: __C.FlutterPluginRegistrar) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "Swift._bridgeAnythingToObjectiveC<A>(A) -> Swift.AnyObject", referenced from:
          function signature specialization <Arg[0] = Dead, Arg[1] = Dead, Arg[2] = Owned To Guaranteed> of function signature specialization <Arg[1] =
          [Closure Propagated : reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.Optional<Swift.AnyObject>)
          -> () to @escaping @callee_guaranteed (@in_guaranteed Swift.Optional<Any>) -> (), Argument Types : [@escaping @callee_unowned
          @convention(block) (@unowned Swift.AnyObject?) -> ()]> of maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result:
          (Any?) -> ()) -> () in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "_swift_getTypeByMangledNameInContext", referenced from:
          ___swift_instantiateConcreteTypeFromMangledName in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "__swift_FORCE_LOAD_$_swiftUIKit", referenced from:
          __swift_FORCE_LOAD_$_swiftUIKit_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftUIKit_$_maps_launcher)
      "Swift.String.append(Swift.String) -> ()", referenced from:
          maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
          function signature specialization <Arg[0] = Dead, Arg[1] = Dead, Arg[2] = Owned To Guaranteed> of function signature specialization <Arg[1] =
          [Closure Propagated : reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.Optional<Swift.AnyObject>)
          -> () to @escaping @callee_guaranteed (@in_guaranteed Swift.Optional<Any>) -> (), Argument Types : [@escaping @callee_unowned
          @convention(block) (@unowned Swift.AnyObject?) -> ()]> of maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result:
          (Any?) -> ()) -> () in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "__swift_FORCE_LOAD_$_swiftDarwin", referenced from:
          __swift_FORCE_LOAD_$_swiftDarwin_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_maps_launcher)
      "_swift_unknownObjectRelease", referenced from:
          static maps_launcher.SwiftMapsLauncherPlugin.register(with: __C.FlutterPluginRegistrar) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
          @objc static maps_launcher.SwiftMapsLauncherPlugin.register(with: __C.FlutterPluginRegistrar) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
          function signature specialization <Arg[0] = Dead, Arg[1] = Dead, Arg[2] = Owned To Guaranteed> of function signature specialization <Arg[1] =
          [Closure Propagated : reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.Optional<Swift.AnyObject>)
          -> () to @escaping @callee_guaranteed (@in_guaranteed Swift.Optional<Any>) -> (), Argument Types : [@escaping @callee_unowned
          @convention(block) (@unowned Swift.AnyObject?) -> ()]> of maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result:
          (Any?) -> ()) -> () in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "static (extension in Foundation):Swift.String._unconditionallyBridgeFromObjectiveC(__C.NSString?) -> Swift.String", referenced from:
          maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
          function signature specialization <Arg[0] = Dead, Arg[1] = Dead, Arg[2] = Owned To Guaranteed> of function signature specialization <Arg[1] =
          [Closure Propagated : reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.Optional<Swift.AnyObject>)
          -> () to @escaping @callee_guaranteed (@in_guaranteed Swift.Optional<Any>) -> (), Argument Types : [@escaping @callee_unowned
          @convention(block) (@unowned Swift.AnyObject?) -> ()]> of maps_launcher.SwiftMapsLauncherPlugin.handle(_: __C.FlutterMethodCall, result:
          (Any?) -> ()) -> () in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "__swift_FORCE_LOAD_$_swiftMetal", referenced from:
          __swift_FORCE_LOAD_$_swiftMetal_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftMetal_$_maps_launcher)
      "_swift_unknownObjectRetain", referenced from:
          @objc static maps_launcher.SwiftMapsLauncherPlugin.register(with: __C.FlutterPluginRegistrar) -> () in
          libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
      "__swift_FORCE_LOAD_$_swiftObjectiveC", referenced from:
          __swift_FORCE_LOAD_$_swiftObjectiveC_$_maps_launcher in libmaps_launcher.a(SwiftMapsLauncherPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftObjectiveC_$_maps_launcher)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by ben55j** [comment]
Here my flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by pikaju** [comment]
Can you please check if the issue persists in version `2.1.0`?
