### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by dna-f** [pikaju/flutter-maps-launcher#12]
Hi, is Null safety migration on roadmap?
Thanks

**Comment by phcs971** [comment]
Hello,
I need the same, and if possible update url_launcher
Thanks

**Comment by orevial** [comment]
Hi, I just proposed a pull request with the null safety migration (and url_launcher upgrade of course): #13

**Comment by erperejildo** [comment]
Looking forward to be merged

**Comment by voivoed** [comment]
+1 on this, please?

**Comment by thherman** [comment]
Looking forward to it as well !

**Comment by pikaju** [comment]
I just published a new version, sorry for the wait!
