### ISSUE TITLE
Upgrade maps_launcher please

### ISSUE THREAD

**Issue by blue492** [pikaju/flutter-maps-launcher#16]
Hi,

You need to upgrade maps_launcher package, because when I tried to upgrade url_launcher to ^6.0.3 it showed me the following:
```
Because maps_launcher 1.2.2+2 depends on url_launcher ^5.5.0 and no versions of maps_launcher match >1.2.2+2 <2.0.0, maps_launcher ^1.2.2+2 requires url_launcher ^5.5.0.
So, because flutter_app depends on both url_launcher ^6.0.3 and maps_launcher ^1.2.2+2, version solving failed.
```

I cannot upgrade url_launcher, can you please maps_launcher  your package because there are many plugins which are depended on url_launcher.

Best Regards

**Comment by pikaju** [comment]
Have you tried version `2.0.0` of the package? It should be using the lastest `url_launcher`.
