### ISSUE TITLE
Freeze when returning back to the app on iOS

### ISSUE THREAD

**Issue by tonnyavery** [pikaju/flutter-maps-launcher#17]
Unfortunately, I don't have any logs.
The app just freezes completely when returning back from iOS maps.

**Comment by shantaly** [comment]
I have a similar issue. Returning back to the app from IOS maps crashes the app for me on IOS version (14.4). Launcher does not work (does not initiate IOS maps) on IOS version (14.3)

**Comment by alymoursy** [comment]
+1 @pikaju

**Comment by tonnyavery** [comment]
You can workaround by setting `forceSafariVC: false`
The real cause is that something is blocking the thread, for me it was another buggy widget on the screen.
When you return back after launching a map url, app can't resume because something is using the thread already and locked it.
Try debugging your and url_launcher to see if this is the cause
