### ISSUE TITLE
how to draw route in iOS apple map? in android google maps, it is showing directions option. but in iOS it is just opening the map only

### ISSUE THREAD

**Issue by MuraliThangavel** [pikaju/flutter-maps-launcher#20]

**Comment by atiqsamtia** [comment]
Facing the same issue

**Comment by kashifniazdev** [comment]
@atiqsamtia @MuraliThangavel Facing the issue, did you guys find any alternative solution? If you guys can share it, It will be a great help.

**Comment by pikaju** [comment]
My current understanding is that you need to pass a label as the third parameter of `launchCoordinates` for a pin to show up. #19
