### ISSUE TITLE
Error launching Waze app

### ISSUE THREAD

**Issue by SamTobias** [pikaju/flutter-maps-launcher#21]
**Description:**
Package doesn't work for Waze app, both query and coordinates opens Waze but shows an error dialog.

![image](https://user-images.githubusercontent.com/13008789/151029097-5155351a-cc80-4a50-9664-f79568e07cd9.png)

**How to reproduce:**
Run example app on Android and launch query or coordinates then select Waze app.

_Tested with version 2.0.1 on Android 9 with Waze installed_

**Comment by SamTobias** [comment]
Changing this line
https://github.com/pikaju/flutter-maps-launcher/blob/05bb182a996c68652dc34eccd0a2081aee0224c2/lib/maps_launcher.dart#L43

to this
```dart
uri = Uri.parse('geo:$latitude,$longitude?q=$query');
```

seems to fix issue for `launchCoordinates`, because apparently Waze needs to receive coordinates after "geo:", but the issue still remains for `launchQuery`

**Comment by pikaju** [comment]
Hey, I'm wondering if this issue still exists a year later?

An argument could be made that this is an issue on Waze' side. The Android documentation has a clear example that uses `geo:0,0`: https://developers.google.com/maps/documentation/urls/android-intents#search-for-a-location

I'll close it for now, please reopen if the issue persists.
