### ISSUE TITLE
Default Apple maps

### ISSUE THREAD

**Issue by ramirezsebas** [pikaju/flutter-maps-launcher#26]
When using IOS, it launches the default app which is Apple Maps. How can i make it list the available navigation apps on IOS?
It works with android.

**Comment by pikaju** [comment]
I might be wrong, but I think this isn't possible on iOS. Apple just wants you to use Apple maps. Check out [map_launcher](https://pub.dev/packages/map_launcher), maybe it is better suited for your use case.
