### ISSUE TITLE
Error launching query Waze app

### ISSUE THREAD

**Issue by yairsts** [pikaju/flutter-maps-launcher#33]
Description:
Package doesn't work for Waze app, query opens Waze but shows an error dialog.
![151029097-5155351a-cc80-4a50-9664-f79568e07cd9](https://github.com/pikaju/flutter-maps-launcher/assets/49818364/98c6971f-dc42-40b0-9d13-22f1ada20ea7)

How to reproduce:
Run example app on Android and launch query then select Waze app.

How to fix:
You need to change this line:

![image](https://github.com/pikaju/flutter-maps-launcher/assets/49818364/37f885b3-fab7-4a87-961f-b1983718a5ce)

Tested with version 2.0.2 on Android 12 with Waze installed

**Comment by pikaju** [comment]
Should be fixed in version 3.0.0. Sorry for the wait.
