### ISSUE TITLE
flutter build apk --flavor development --target lib/main_development.dart

### ISSUE THREAD

**Issue by Jules369-ZM** [pikaju/flutter-maps-launcher#36]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':maps_launcher'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 26s

**Comment by Alkmaar072** [comment]
I have the same issue.

**Comment by IvanKastorsky** [comment]
Same here

**Comment by pikaju** [comment]
Should be fixed in version 3.0.0. Could you check if it works? Sorry for the wait. Please reopen another issue if necessary.
