### ISSUE TITLE
Support for WebAssembly (Wasm)

### ISSUE THREAD

**Issue by arnaudruffin** [pikaju/flutter-maps-launcher#46]
Since a few month Flutter stable release support web assembly: https://docs.flutter.dev/platform-integration/web/wasm
Currently the latest published version of flutter-maps-launcher does not support web assembly.

I haven't checked in detail, but I think that for "flutter-maps-launcher" to be compliant it would only need to migrate to package:web.
https://dart.dev/interop/js-interop/package-web

I am willing to contribute if needed.

**Comment by arnaudruffin** [comment]
After having a look it is even simplier : the JS interop that is causing the issue can be updated with the new package:web, but it seems that it is only used to implement 'getPlatformVersion' method, which does not exist in the interface.

This must be a leftover from the initial plugin template.

Deleting this method would do.

**Comment by pikaju** [comment]
Hey, with version 3.0.0, WASM should now be working. Could you check again and open another issue if necessary? Sorry for the wait.
