### ISSUE TITLE
Extend iOS part to support native navigation

### ISSUE THREAD

**Issue by tonnyavery** [pikaju/flutter-maps-launcher#5]
Instead of just firing a URL, plugin could run some custom code that would allow iOS devices to show a list of suggestions to pick from when navigating
https://stackoverflow.com/questions/28604429/how-to-open-maps-app-programmatically-with-coordinates-in-swift

**Comment by pikaju** [comment]
Maybe the [map_launcher](https://github.com/mattermoran/map_launcher) plugin is more suited for this use case.
