### ISSUE TITLE
lunch maps app with direction or two location to route in map

### ISSUE THREAD

**Issue by mshamsi502** [pikaju/flutter-maps-launcher#7]
how can I launch the map of another app with Direction(or Route or two locations) data (every app! no like [`map_launcher`](https://github.com/mattermoran/map_launcher) that launch just some apps ) 
some like [`Intent`](https://pub.dev/packages/intent/example) package and `ACTION_VIEW` :
```
                    android_intent.Intent()
                      ..setAction(android_action.Action.ACTION_VIEW)
                      ..setData(
                        Uri.parse(
                            "http://maps.google.com/maps?saddr=17.428323,78.412567&daddr=28.6454414,77.0907573"),
                      )
                      ..startActivityForResult().then(
                        (data) => print(data),
                      );
```
but i want user select app by` open with`

**Comment by pikaju** [comment]
I think this may be impossible because the `geo` intent on Android doesn't have this feature. I couldn't find it at least. They only explain how to do it with Google Maps only, like you described.
